//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlBulkUpsert.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlBulkUpsert.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///USE [master]
        ///GO
        ///
        ////****** Object:  Database [SqlBulkUpsertTestDb]    Script Date: 02/10/2011 22:47:12 ******/
        ///IF  EXISTS (SELECT name FROM sys.databases WHERE name = N&apos;SqlBulkUpsertTestDb&apos;)
        ///DROP DATABASE [SqlBulkUpsertTestDb]
        ///GO
        ///
        ///USE [master]
        ///GO
        ///
        ////****** Object:  Database [SqlBulkUpsertTestDb]    Script Date: 02/10/2011 22:47:12 ******/
        ///CREATE DATABASE [SqlBulkUpsertTestDb]
        ///GO
        ///
        ///USE [SqlBulkUpsertTestDb]
        ///GO
        ///
        ////****** Object:  Table [dbo].[TestUpsert]    Script Date: 02/10/2011 22:48:06 **** [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseSchemaRefresh {
            get {
                return ResourceManager.GetString("DatabaseSchemaRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [SqlBulkUpsertTestDb]
        ///GO
        ////****** Object:  Table [dbo].[TestUpsert]    Script Date: 05/08/2011 02:35:07 ******/
        ///SET IDENTITY_INSERT [dbo].[TestUpsert] ON
        ///INSERT [dbo].[TestUpsert] ([ident], [key_part_1], [key_part_2], [nullable_text], [nullable_number], [nullable_datetimeoffset], [nullable_money], [nullable_varbinary], [nullable_image], [nullable_xml]) VALUES (1, N&apos;TEST&apos;, 1, N&apos;some text here 1&apos;, 11, NULL, NULL, NULL, NULL, NULL)
        ///INSERT [dbo].[TestUpsert] ([ident], [key_part_1], [key_part_2], [nullab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PopulateTable {
            get {
                return ResourceManager.GetString("PopulateTable", resourceCulture);
            }
        }
    }
}
